name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.24
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: terraform init
      - run: terraform plan -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var="tenant_id=${{ secrets.tenantId }}" -var="client_id=${{ secrets.servicePrincipalId }}" -var="client_secret=${{ secrets.servicePrincipalKey }}"


      #          ls -Flah
#          echo ${{ secrets.rg }}
#          az network vnet create -g contoso -n contoso-vnet
    #terraform plan
    #az webapp list --query "[?state=='Running']"
