name: TF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.0.1
      with:
        terraform_version: 0.12.24
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az network vnet create -g contoso -n contoso-vnet
    - run: |
           terraform init
           terraform plan -out vnet.tfplan input=false \
            -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
            -var="tenant_id=${{ secrets.tenantId }}" \
            -var="client_id=${{ secrets.servicePrincipalId }}" \
            -var="client_secret=${{ secrets.servicePrincipalKey }}"
           az network vnet create -g contoso -n contoso-vnet
           
